#pragma config(Sensor, dgtl2,  rightSonar,     sensorSONAR_inch)
#pragma config(Sensor, dgtl4,  leftSonar,      sensorSONAR_inch)
#pragma config(Sensor, dgtl6,  frontSonar,     sensorSONAR_inch)
#pragma config(Motor,  port2,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           Arm,           tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           Claw,          tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           rightMotor,    tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/* void backUp(float time)
{
	motor[rightMotor] = -65.4;
	motor[leftMotor] = -63;
	wait1Msec(time);
}
*/

void rotate(float time, int t)  //t = left or right, 1 is TURN right, 2 is TURN left
{
	switch (t)
	{
		case 1:
			motor[rightMotor] = -127;		  // Motor on port2 is run at full (-127) power reverse
			motor[leftMotor]  = 127;
			wait1Msec(time);
			break;
		case 2:
			motor[rightMotor] = 127;		  // Motor on port2 is run at full (-127) power reverse
			motor[leftMotor]  = -127;
			wait1Msec(time);
			break;
	}
}

void stopBoth(float time)
{
	stopMotor(rightMotor);
	stopMotor(leftMotor);
	wait1Msec(time);
}

void moveArm(float time, float speed)
{
	motor[Arm] = speed;
	wait1Msec(time);
}

void moveClaw(float time, float speed)
{
	motor[Claw] = speed;
	wait1Msec(time);
}


task main()
{
	moveArm(300, 63);
	moveArm(300, -63);
	moveClaw(300, 63);
	moveClaw(300, -63);
	int frontValue;
	int rightValue;
	motor[rightMotor] = 65.4;
	motor[leftMotor] = 63;
	wait1Msec(1000);

	while(true)
	{
		frontValue = SensorValue(frontSonar);
		rightValue = SensorValue(rightSonar);

		if (rightValue > 12)  // Turn right if the path is clear
	        {
	        		wait(0.5);
	            stopBoth(1000);
	            rotate(850, 1);  // Rotate right
	            motor[rightMotor] = 65.4;
							motor[leftMotor] = 63;
							wait(2)
	        }
    else if (frontValue < 6)  // Turn left if there's an obstacle in front
			    {
			        stopBoth(1000);
			        rotate(500, 2);  // Rotate left
			    }
    else  // Move forward
			    {
			        motor[rightMotor] = 65.4;
			        motor[leftMotor] = 63;

			    }
	}


}
