#pragma config(Sensor, dgtl2,  rightSonar,     sensorSONAR_inch)
#pragma config(Sensor, dgtl4,  leftSonar,      sensorSONAR_inch)
#pragma config(Sensor, dgtl6,  frontSonar,     sensorSONAR_inch)
#pragma config(Motor,  port2,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port9,           rightMotor,    tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void backUp(float time)
{
	motor[rightMotor] = -65.4;
	motor[leftMotor] = -63;
	wait1Msec(time);
}

void rotate(float time, int t)  //t = left or right, 1 is TURN right, 2 is TURN left
{
	switch (t)
	{
		case 1:
			motor[rightMotor] = -127;		  // Motor on port2 is run at full (-127) power reverse
			motor[leftMotor]  = 127;
			wait1Msec(time);
		case 2:
			motor[rightMotor] = 127;		  // Motor on port2 is run at full (-127) power reverse
			motor[leftMotor]  = -127;
			wait1Msec(time);
	}
}

void stopBoth()
{
	stopMotor(rightMotor);
	stopMotor(leftMotor);
}

void straigten()
{
	float rightSpeed = 65.4;
	float leftSpeed = 63;
	int frontValue;
	int leftValue;
	int rightValue;
	int difference;
	motor[rightMotor] = rightSpeed;
	motor[leftMotor] = leftSpeed;
	frontValue = SensorValue(frontSonar);
	leftValue = SensorValue(leftSonar);
	rightValue = SensorValue(rightSonar);
	difference = rightValue - leftValue;
	if (difference > 5 && rightValue < 8)   // difference > 2 means the robo should turn RIGHT
	{
	rightSpeed = rightSpeed - 1.5;
	}
	if (difference < -5 && rightValue > -8)   // difference > 2 means the robo should turn RIGHT
	{
		rightSpeed = rightSpeed + 1.5;
	}

}

task main()
{
	int frontValue;
	int leftValue;
	int rightValue;
	int difference;


	while(true)
	{
		while(SensorValue(frontSonar) > 6)
		{
			straigten();
		}
		wait1Msec(2000);
		if (frontValue < 6)
			{
				stopBoth();
				difference = rightValue - leftValue;
				if (difference > 5)   // difference > 2 means the robo should turn RIGHT
				{
					backUp(300);
					rotate(750, 1);
				}
				else if (difference < -5) // turn LEFT
				{
					backUp(300);
					rotate(750, 2);
				}
				else
				{
					difference = 0;
					frontValue = 0;
					leftValue = 0;
					rightValue = 0;
				}
			}
	}


}
