
#pragma config(Sensor, dgtl2,  rightSonar,     sensorSONAR_inch)
#pragma config(Sensor, dgtl4,  leftSonar,      sensorSONAR_inch)
#pragma config(Sensor, dgtl6,  frontSonar,     sensorSONAR_inch)
#pragma config(Motor,  port2,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           Arm,           tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           Claw,          tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           rightMotor,    tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
#include <stdio.h> 
#include <stdlib.h>
*/

/* void backUp(float time)
{
	motor[rightMotor] = -65.4;
	motor[leftMotor] = -63;
	wait1Msec(time);
}
*/

void rotate(int t)  //t = left or right, 1 is TURN right, 2 is TURN left
{
	switch (t)
	{
		case 1:
			motor[rightMotor] = -127;		  // Motor on port2 is run at full (-127) power reverse
			motor[leftMotor]  = 127;

			break;
		case 2:
			motor[rightMotor] = 127;		  // Motor on port2 is run at full (-127) power reverse
			motor[leftMotor]  = -127;

			break;
	}
}

void stopBoth(float time)
{
	stopMotor(rightMotor);
	stopMotor(leftMotor);
	wait1Msec(time);
}

void moveArm(float speed)
{
	motor[Arm] = speed;
	motor[Arm] = 0;
}

void moveClaw(float speed)
{
	motor[Claw] = speed;
	motor[Claw] = 0;
}

void moveStuff()
{
	int randome = random(2);
	if (randome == 0)
	{
		moveArm(63);
		moveClaw(63);
	}
	else
	{
		moveArm(-63);
		moveClaw(-63);
	}
}
	


task main()
{
	int frontValue;
	int rightValue;
	motor[rightMotor] = 65.4;
	motor[leftMotor] = 63;
	wait1Msec(1000);

	while(true)
	{
		frontValue = SensorValue(frontSonar);
		rightValue = SensorValue(rightSonar);
		if (rightValue > 12)
			{
				wait(0.5);
				stopBoth(1000);
				while (SensorValue(frontSonar) < 12)
				{
					rotate(1);
					moveStuff();
				}
				stopBoth(250);
				motor[rightMotor] = 65.4;
				motor[leftMotor] = 63;
			}
		else if (frontValue < 6)
			{
				wait(0.5);
				stopBoth(1000);
				while (SensorValue(frontSonar) < 12)
				{
					rotate(2);
					moveStuff();
				}
				stopBoth(250);
			}
		
		else
			{
			        motor[rightMotor] = 65.4;
			        motor[leftMotor] = 63;
				moveStuff();

			}


		
	}


}
